In [50]:
import pandas as pd

In [51]:
file_path = "/kaggle/input/loan-predication/train_u6lujuX_CVtuZ9i (1).csv"
df = pd.read_csv(file_path)

df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [52]:
df[ df.duplicated() ]

Empty DataFrame
Columns: [Loan_ID, Gender, Married, Dependents, Education, Self_Employed, ApplicantIncome, CoapplicantIncome, LoanAmount, Loan_Amount_Term, Credit_History, Property_Area, Loan_Status]
Index: []

In [53]:
df.loc[614] = df.loc[613]
df.tail()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N
614,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [54]:
df[ df.duplicated() ]

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
614,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [55]:
#df = df.dropna()
#df

In [56]:
g_mode = df['Gender'].mode()
g_mode = g_mode.values[0]
g_mode

'Male'

In [57]:
df['Gender'] = df['Gender'].fillna(g_mode)
df.isna().sum()

Loan_ID               0
Gender                0
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [58]:
m_mode = df['Married'].mode()
m_mode = m_mode.values[0]
m_mode

'Yes'

In [59]:
df['Married'] = df['Married'].fillna(m_mode)
df.isna().sum()

Loan_ID               0
Gender                0
Married               0
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [60]:
d_mode = df['Dependents'].mode()
d_mode = d_mode.values[0]
d_mode

'0'

In [61]:
df['Dependents'] = df['Dependents'].fillna(d_mode)
df.isna().sum()

Loan_ID               0
Gender                0
Married               0
Dependents            0
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [62]:
s_mode = df['Self_Employed'].mode()
s_mode = s_mode.values[0]
s_mode

'No'

In [63]:
df['Self_Employed'] = df['Self_Employed'].fillna(s_mode)
df.isna().sum()

Loan_ID               0
Gender                0
Married               0
Dependents            0
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [64]:
c_mode = df['Credit_History'].mode()
c_mode = c_mode.values[0]
c_mode

np.float64(1.0)

In [65]:
df['Credit_History'] = df['Credit_History'].fillna(c_mode)
df.isna().sum()

Loan_ID               0
Gender                0
Married               0
Dependents            0
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History        0
Property_Area         0
Loan_Status           0
dtype: int64

In [66]:
l_mean = df['LoanAmount'].mean()
l_mean

np.float64(146.38954468802697)

In [67]:
df['LoanAmount'] = df['LoanAmount'].fillna(l_mean)
df.isna().sum()

Loan_ID               0
Gender                0
Married               0
Dependents            0
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term     14
Credit_History        0
Property_Area         0
Loan_Status           0
dtype: int64

In [68]:
la_mean = df['Loan_Amount_Term'].mean()
la_mean

np.float64(342.02995008319465)

In [69]:
df['Loan_Amount_Term'] = df['Loan_Amount_Term'].fillna(la_mean)
df.isna().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [70]:
df.isna().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [71]:
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,146.389545,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.000000,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.000000,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.000000,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.000000,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.000000,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.000000,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.000000,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.000000,360.0,0.0,Semiurban,N
614,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.000000,360.0,0.0,Semiurban,N

In [72]:
df['CoapplicantIncome'] = df['CoapplicantIncome'].astype(int)
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0,146.389545,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508,128.000000,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0,66.000000,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358,120.000000,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0,141.000000,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,LP002979,Male,Yes,3+,Graduate,No,4106,0,40.000000,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240,253.000000,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0,187.000000,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0,133.000000,360.0,0.0,Semiurban,N
614,LP002990,Female,No,0,Graduate,Yes,4583,0,133.000000,360.0,0.0,Semiurban,N

In [73]:
df['LoanAmount'] = df['LoanAmount'].astype(int)
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0,146,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508,128,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0,66,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358,120,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0,141,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,LP002979,Male,Yes,3+,Graduate,No,4106,0,40,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240,253,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0,187,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0,133,360.0,0.0,Semiurban,N
614,LP002990,Female,No,0,Graduate,Yes,4583,0,133,360.0,0.0,Semiurban,N

In [74]:
df['Credit_History'] = df['Credit_History'].astype(int)
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0,146,360.0,1,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508,128,360.0,1,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0,66,360.0,1,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358,120,360.0,1,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0,141,360.0,1,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,LP002979,Male,Yes,3+,Graduate,No,4106,0,40,180.0,1,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240,253,360.0,1,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0,187,360.0,1,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0,133,360.0,0,Semiurban,N
614,LP002990,Female,No,0,Graduate,Yes,4583,0,133,360.0,0,Semiurban,N

In [75]:
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0,146,360.0,1,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508,128,360.0,1,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0,66,360.0,1,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358,120,360.0,1,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0,141,360.0,1,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,LP002979,Male,Yes,3+,Graduate,No,4106,0,40,180.0,1,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240,253,360.0,1,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0,187,360.0,1,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0,133,360.0,0,Semiurban,N
614,LP002990,Female,No,0,Graduate,Yes,4583,0,133,360.0,0,Semiurban,N

In [76]:
import plotly.express as px
import plotly.io as pio
pio.renderers.default ='iframe'

In [77]:
    gender_vc = df['Gender'].value_counts()

fig = px.bar(x=gender_vc.index, y = gender_vc.values, color=gender_vc.index )
fig

In [78]:
fig = px.pie(names=gender_vc.index, values = gender_vc.values, hole=0.5 )
fig

In [79]:
married_vc = df['Married'].value_counts()

fig = px.bar(x=married_vc.index, y = married_vc.values, color=married_vc.index )
fig

In [80]:
Education_vc = df['Education'].value_counts()

fig = px.bar(x=Education_vc.index, y = Education_vc.values, color=Education_vc.index )
fig

In [81]:
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0,146,360.0,1,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508,128,360.0,1,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0,66,360.0,1,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358,120,360.0,1,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0,141,360.0,1,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,LP002979,Male,Yes,3+,Graduate,No,4106,0,40,180.0,1,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240,253,360.0,1,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0,187,360.0,1,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0,133,360.0,0,Semiurban,N
614,LP002990,Female,No,0,Graduate,Yes,4583,0,133,360.0,0,Semiurban,N

In [82]:
fig = px.sunburst(df, path = ["Education","Married","Gender","Property_Area" ], values = "LoanAmount")
fig

In [83]:
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0,146,360.0,1,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508,128,360.0,1,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0,66,360.0,1,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358,120,360.0,1,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0,141,360.0,1,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,LP002979,Male,Yes,3+,Graduate,No,4106,0,40,180.0,1,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240,253,360.0,1,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0,187,360.0,1,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0,133,360.0,0,Semiurban,N
614,LP002990,Female,No,0,Graduate,Yes,4583,0,133,360.0,0,Semiurban,N

In [84]:
fig = px.histogram(df, x = ['ApplicantIncome', 'CoapplicantIncome'])
fig

In [85]:
fig = px.treemap(df, path = ["Education","Married","Gender","Property_Area" ], values = "LoanAmount")
fig.show()

In [86]:
fig = px.scatter(df, x = 'ApplicantIncome', y = 'LoanAmount', color = 'Loan_Status')
fig

In [87]:
fig = px.scatter_3d(df, x = 'ApplicantIncome', y = 'LoanAmount', z='LoanAmount', color = 'Loan_Status')
fig

In [88]:
y = df['Loan_Status']
y

0      Y
1      N
2      Y
3      Y
4      Y
      ..
610    Y
611    Y
612    Y
613    N
614    N
Name: Loan_Status, Length: 615, dtype: object

In [89]:
X = df.drop("Loan_Status", axis = 1)
X.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001002,Male,No,0,Graduate,No,5849,0,146,360.0,1,Urban
1,LP001003,Male,Yes,1,Graduate,No,4583,1508,128,360.0,1,Rural
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0,66,360.0,1,Urban
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358,120,360.0,1,Urban
4,LP001008,Male,No,0,Graduate,No,6000,0,141,360.0,1,Urban

In [90]:
y = df['Loan_Status']
y

0      Y
1      N
2      Y
3      Y
4      Y
      ..
610    Y
611    Y
612    Y
613    N
614    N
Name: Loan_Status, Length: 615, dtype: object

In [91]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])

df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,1,No,0,Graduate,No,5849,0,146,360.0,1,Urban,Y
1,LP001003,1,Yes,1,Graduate,No,4583,1508,128,360.0,1,Rural,N
2,LP001005,1,Yes,0,Graduate,Yes,3000,0,66,360.0,1,Urban,Y
3,LP001006,1,Yes,0,Not Graduate,No,2583,2358,120,360.0,1,Urban,Y
4,LP001008,1,No,0,Graduate,No,6000,0,141,360.0,1,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,LP002979,1,Yes,3+,Graduate,No,4106,0,40,180.0,1,Rural,Y
611,LP002983,1,Yes,1,Graduate,No,8072,240,253,360.0,1,Urban,Y
612,LP002984,1,Yes,2,Graduate,No,7583,0,187,360.0,1,Urban,Y
613,LP002990,0,No,0,Graduate,Yes,4583,0,133,360.0,0,Semiurban,N
614,LP002990,0,No,0,Graduate,Yes,4583,0,133,360.0,0,Semiurban,N

In [92]:
df = df.drop(['Loan_ID'], axis = 1)
df

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,1,No,0,Graduate,No,5849,0,146,360.0,1,Urban,Y
1,1,Yes,1,Graduate,No,4583,1508,128,360.0,1,Rural,N
2,1,Yes,0,Graduate,Yes,3000,0,66,360.0,1,Urban,Y
3,1,Yes,0,Not Graduate,No,2583,2358,120,360.0,1,Urban,Y
4,1,No,0,Graduate,No,6000,0,141,360.0,1,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
610,1,Yes,3+,Graduate,No,4106,0,40,180.0,1,Rural,Y
611,1,Yes,1,Graduate,No,8072,240,253,360.0,1,Urban,Y
612,1,Yes,2,Graduate,No,7583,0,187,360.0,1,Urban,Y
613,0,No,0,Graduate,Yes,4583,0,133,360.0,0,Semiurban,N
614,0,No,0,Graduate,Yes,4583,0,133,360.0,0,Semiurban,N

In [93]:
df

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,1,No,0,Graduate,No,5849,0,146,360.0,1,Urban,Y
1,1,Yes,1,Graduate,No,4583,1508,128,360.0,1,Rural,N
2,1,Yes,0,Graduate,Yes,3000,0,66,360.0,1,Urban,Y
3,1,Yes,0,Not Graduate,No,2583,2358,120,360.0,1,Urban,Y
4,1,No,0,Graduate,No,6000,0,141,360.0,1,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
610,1,Yes,3+,Graduate,No,4106,0,40,180.0,1,Rural,Y
611,1,Yes,1,Graduate,No,8072,240,253,360.0,1,Urban,Y
612,1,Yes,2,Graduate,No,7583,0,187,360.0,1,Urban,Y
613,0,No,0,Graduate,Yes,4583,0,133,360.0,0,Semiurban,N
614,0,No,0,Graduate,Yes,4583,0,133,360.0,0,Semiurban,N

In [94]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])
df['Married'] = le.fit_transform(df['Married'])
df['Education'] = le.fit_transform(df['Education'])
df['Self_Employed'] = le.fit_transform(df['Self_Employed'])
df['Property_Area'] = le.fit_transform(df['Property_Area'])
df['Dependents'] = le.fit_transform(df['Dependents'])
df

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,1,0,0,0,0,5849,0,146,360.0,1,2,Y
1,1,1,1,0,0,4583,1508,128,360.0,1,0,N
2,1,1,0,0,1,3000,0,66,360.0,1,2,Y
3,1,1,0,1,0,2583,2358,120,360.0,1,2,Y
4,1,0,0,0,0,6000,0,141,360.0,1,2,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
610,1,1,3,0,0,4106,0,40,180.0,1,0,Y
611,1,1,1,0,0,8072,240,253,360.0,1,2,Y
612,1,1,2,0,0,7583,0,187,360.0,1,2,Y
613,0,0,0,0,1,4583,0,133,360.0,0,1,N
614,0,0,0,0,1,4583,0,133,360.0,0,1,N